### ISSUE TITLE
Error while parsing config file: 'str' object has no attribute 'error' (traceback in logfile)

### ISSUE THREAD

**Issue by lquinet** [rockwelln/buildbot-slack#8]
Hi,

There is an error due to the use of the attribute "error" which doesn't exist for a string in reporter.py at these lines:

```python
        if not isinstance(endpoint, str):
            endpoint.error("endpoint must be a string")
        elif not endpoint.startswith("http"):
            endpoint.error('endpoint should start with "http..."')
        if channel and not isinstance(channel, str):
            channel.error("channel must be a string")
        if username and not isinstance(username, str):
            username.error("username must be a string")
        if host_url and not isinstance(host_url, str):  # deprecated
            host_url.error("host_url must be a string")
```

This create the following error when I launch buildbot:

```sh
buildbot_1  | error while parsing config file:
buildbot_1  | Traceback (most recent call last):
buildbot_1  |   File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
buildbot_1  |     result = f(*args, **kw)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/scripts/upgrade_master.py", line 128, in upgradeMaster
buildbot_1  |     master_cfg = base.loadConfig(config, configFile)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/scripts/base.py", line 112, in loadConfig
buildbot_1  |     config['basedir'], configFileName).loadConfig()
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/config.py", line 166, in loadConfig
buildbot_1  |     self.basedir, self.configFileName)
buildbot_1  | --- <exception caught here> ---
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/config.py", line 128, in loadConfigDict
buildbot_1  |     execfile(filename, localDict)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/twisted/python/compat.py", line 247, in execfile
buildbot_1  |     exec(code, globals, locals)
buildbot_1  |   File "/var/lib/buildbot/master.cfg", line 256, in <module>
buildbot_1  |     endpoint=os.environ.get("SLACK_WEBHOOK_URL", ""),
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/util/service.py", line 180, in __init__
buildbot_1  |     self.checkConfig(*args, **kwargs)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot_slack/reporter.py", line 46, in checkConfig
buildbot_1  |     endpoint.error('endpoint should start with "http..."')
buildbot_1  | builtins.AttributeError: 'str' object has no attribute 'error'
buildbot_1  | 
buildbot_1  | checking basedir
buildbot_1  | checking for running master
buildbot_1  | checking master.cfg
buildbot_1  | Errors loading configuration:
buildbot_1  |   error while parsing config file: 'str' object has no attribute 'error' (traceback in logfile)
buildbot_1  | Can't upgrade master yet. Waiting for database ready?
```

I am using buildbot with docker and I installed it in the container with `pip3 install buildbot-slack`

**Comment by rockwelln** [comment]
Indeed, thank you for reporting this.
In the meantime, to solve your problem, simply provide the entire URL as the endpoint.
The endpoint should look like https://hooks.slack.com/services/.../...

**Comment by lquinet** [comment]
Well, for a strange reason the method `os.environ.get()` used in master.cfg to get environnent variable in master container doesn't behave well with your reporter... 

At the step "parsing config file" the environnement variable is not recognised but at the step "checking master.cfg" yes (I printed out the variable). I've already used that with GitHubStatusPush and I didn't have any problems.

code in master.cfg:
```python
webhook = os.environ.get("SLACK_WEBHOOK_URL", "https://fakewebhook")
print("Webhook: {}".format(webhook))

ss = reporters.SlackStatusPush(
    endpoint=webhook,
)
c['services'].append(ss)
```

As you can see in the error (hided real slack webhook):

```sh
buildbot_1  | error while parsing config file:
buildbot_1  | Traceback (most recent call last):
buildbot_1  |   File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
buildbot_1  |     result = f(*args, **kw)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/scripts/upgrade_master.py", line 128, in upgradeMaster
buildbot_1  |     master_cfg = base.loadConfig(config, configFile)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/scripts/base.py", line 112, in loadConfig
buildbot_1  |     config['basedir'], configFileName).loadConfig()
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/config.py", line 166, in loadConfig
buildbot_1  |     self.basedir, self.configFileName)
buildbot_1  | --- <exception caught here> ---
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/config.py", line 128, in loadConfigDict
buildbot_1  |     execfile(filename, localDict)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/twisted/python/compat.py", line 247, in execfile
buildbot_1  |     exec(code, globals, locals)
buildbot_1  |   File "/var/lib/buildbot/master.cfg", line 247, in <module>
buildbot_1  |     endpoint=webhook,
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot/util/service.py", line 180, in __init__
buildbot_1  |     self.checkConfig(*args, **kwargs)
buildbot_1  |   File "/usr/lib/python3.6/site-packages/buildbot_slack/reporter.py", line 46, in checkConfig
buildbot_1  |     endpoint.error('endpoint should start with "http..."')
buildbot_1  | builtins.AttributeError: 'str' object has no attribute 'error'
buildbot_1  | 
buildbot_1  | checking basedir
buildbot_1  | checking for running master
buildbot_1  | checking master.cfg
buildbot_1  | Webhook: "https://hooks.slack.com/services/****************************"
buildbot_1  | Errors loading configuration:
buildbot_1  |   error while parsing config file: 'str' object has no attribute 'error' (traceback in logfile)
buildbot_1  | Can't upgrade master yet. Waiting for database ready?
```

**Comment by rockwelln** [comment]
I started fixing the function checkConfig.
But, your log indicates something (may be) interesting:
if the variable webhook would be correct, the output of: 
`print("Webhook: {}".format(webhook))`
should be:
`Webhook: https://hooks.slack.com/services/****************************`
and not:
`Webhook: "https://hooks.slack.com/services/****************************"`

And this is probably why the function checkConfig is failing on the test `elif not endpoint.startswith("http"):`: the endpoint doesn't starts with http, but "http

**Comment by lquinet** [comment]
Oh thanks a lot for your clue, it turns out that it was the problem. I can't believe it was as simple!
